config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'families#index'

  get 'admin', to: 'admin/dashboards#index'
  get 'admin/dashboard', to: 'admin/dashboards#index'

  namespace :admin do
    resources :families do
      collection { post :import }
      collection { get :qrcodes, defaults: { format: :pdf } }
    end
    resources :guests
    resources :messages
    resources :posts
  end

  resources :families, only: %i[index update] do
    collection { get :login }
    resources :guests, only: %i[show update]
    resources :messages, only: %i[create show update]
  end
  resources :posts
end

app/models/family.rb
class Family < ApplicationRecord
  has_one_attached :photo
  has_many :guests, dependent: :destroy
  has_one :message, dependent: :destroy

  validates :name, presence: true
  validates :email, uniqueness: true, allow_blank: true, if: :will_save_change_to_email?
  validates :uuid, uniqueness: true

  accepts_nested_attributes_for :guests
  accepts_nested_attributes_for :message

  scope :responded, -> { where(response: true).order(updated_at: :desc) }
  scope :not_responded, -> { where(response: false).order(updated_at: :desc) }

  def self.import(file)
    accepted_extensions = ['.xls', '.xlsx']
    return unless accepted_extensions.include? File.extname(file.original_filename).downcase

    spreadsheet = Roo::Spreadsheet.open(file)
    spreadsheet.each_with_pagename do |name, sheet|
      next unless name == 'Uitnodigingen'

      read_sheet sheet
    end
  end

  def qrcode
    qrcode = RQRCode::QRCode.new("https://www.bruiloftsamuelencorine.nl/?uuid=" + uuid)
    qrcode.as_svg(
      offset: 0, color: '000',
      shape_rendering: 'crispEdges',
      module_size: 3
    )
  end

  def photo_url
    Rails.application.routes.url_helpers.rails_blob_path(self.photo, only_path: true)
  end

  private

  def self.read_sheet(sheet)
    sheet.parse headers: true
    sheet.parse header_search: ['Huishouden', 'Gast', 'Dag gasten', 'Avond gasten', 'Kind', 'Dïeet', 'Notities', 'E-mailadres', 'Telefoonnummer']
    sheet.each_with_index(family: 'Huishouden', guest: 'Gast', day_guest: 'Dag gasten', email: 'E-mailadres') do |guest, idx|
      next if idx.zero?

      import_guest guest
    end
  end

  def self.import_guest(guest)
    return if guest[:guest].blank?

    email = Family.set_email guest
    family = guest[:family] ? Family.create!(name: guest[:family], email: email, response: false, uuid: SecureRandom.hex(3)) : Family.last
    Guest.find_or_create_by!(name: guest[:guest], day_guest: (guest[:day_guest] == 1 ? true : false), family: family)
  end

  def self.set_email(guest)
    guest[:email] == '-' ? nil : guest[:email]
  end
end

app/controllers/admin/families_controller.rb
class Admin::FamiliesController < AdminController
  before_action :set_family, only: [:show, :edit, :update, :destroy, :qrcode]
  
  def index
    @families = Family.all
    @families.where!("name ILIKE ? OR email ILIKE ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search]
    @target = params[:target] if params[:target]
    @families = @families.order(params[:order]).page(params[:page]).per_page(20)
    @items = @families
  end

  def show
    respond_with :admin, @family
  end

  def new
    @item = Family.new
  end

  def create
    params[:family][:uuid] = SecureRandom.hex 3
    @family = Family.create family_params
    respond_with :admin, @family
  end

  def edit
    respond_with @family
  end

  def update
    @family.update family_params
    respond_with :admin, @family
  end

  def destroy
    @family.destroy
    redirect_to admin_families_path
  end

  def import
    file = params[:file]
    Family.import file
    redirect_to admin_families_path
  end

  def qrcodes
    @families = Family.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "wedding_qrcodes",
               template: "admin/families/qrcodes.html.erb",
               layout: "pdf.html.erb"
      end
    end
  end

  private

  def family_params
    params.require(:family).permit(:email, :name, :response, :attendees, :photo, :uuid, guests_attributes: [:attending, :id, :day_guest], message_attributes: [:content, :id])
  end

  def set_family
    @family = Family.find params[:id]
    @item = @family
  end
end

app/controllers/families_controller.rb
# frozen_string_literal: true

class FamiliesController < ApplicationController
  before_action :set_family, only: [:update]

  def index; end

  def update
    success = @family.update! family_params
    render json: { success: success, family: @family, photo_url: @family.photo_url }
  end

  def login
    @family = Family.find_by(uuid: params[:uuid]) if params[:uuid]
    return head(:not_found) unless @family

    render json: @family, photo_url: @family&.photo_url, include: %i[guests message]
  end

  private

  def family_params
    params.require(:family).permit(
      :response,
      :photo,
      :allergies,
      guests_attributes: %i[id attending],
      message_attributes: %i[content id]
    )
  end

  def set_family
    @family = Family.find params[:id]
  end
end

app/helpers/families_helper.rb
module FamiliesHelper
  def boolean_icon(responded)
    if responded
      tag.i class: 'fas fa-check'
    else
      tag.i class: 'fas fa-times'
    end
  end

  def atteding_total_guests(family)
    attending = family.guests.map { |guest| true if guest.attending.present? }.compact.count
    "#{attending} / #{family.guests.count}"
  end

  def response_badge(family)
    badge_class = family.response ? 'badge badge-success' : 'badge badge-danger'
    badge_text = family.response ? 'responded' : 'no response'
    tag.span class: badge_class do
      badge_text
    end
  end

  def badge_code(family)
    tag.span family.uuid, class: 'badge badge-secondary', title: 'Wedding code'
  end

  def badge_attending(guest)
    badge_class = guest.attending ? 'badge badge-success' : 'badge badge-danger'
    tag.span class: badge_class do
      guest.attending || 'no response'
    end
  end
end

app/views/admin/families/_family.html.erb
<li class='list-group-item'>
  <div class="d-flex flex-row">
    <div class='pr-3'>
      <% if family.photo.attached? %> 
        <td class="text-center d-none d-lg-table-cell"><%= image_tag family.photo, class: "thumbnail" %></td>
      <% else %>
        <td class="text-center d-none d-lg-table-cell"><%= image_tag 'no_image_available.svg', class: 'thumbnail' %></td>
      <% end %>
    </div>
    <div>
      <div><%= link_to family.name, admin_family_path(family) %></div>
      <div class="d-flex flex-row text-muted">
        <div>
          <small>
            <span class='mr-2'>Guests</span>
            <%= atteding_total_guests family %>
          </small>
        </div>
        <% if family.email.present? %>
          <div>&ensp;&bull;&ensp;<small><%= mail_to_if family.email %></small></div>
        <% end %>
        <% if family.message&.content.present? %>
          <div>&ensp;&bull;&ensp;<small><%= family.message.content.truncate(27) %></small></div>
        <% end %>
      </div>
    </div>
    <div class='ml-auto'>
      <div class='text-right'><%= response_badge family %></div>
      <div class='text-right'><%= badge_code family %></div>
    </div>
  </div>
  <div class='d-flex flex-row'>
    <div><%= family.allergies %></div>
  </div>
  <div class="d-flex flex-row">
    
  </div>
</li>

app/views/admin/families/_form.html.erb
<%= form_for [:admin, @item], html: { class: "needs-validation", novalidate: true } do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: true, autocomplete: "off" %>
    <div class="invalid-feedback"></div>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control", autocomplete: "off" %>
    <div class="invalid-feedback"></div>
  </div>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control", autocomplete: "off", style: "display:none", id: "real-input-field" %>
    <div class="input-group">
      <%= text_field_tag :visible_file_upload_field, nil, class: "form-control", autocomplete: "off", required: true %>
      <div class="input-group-append">
        <%= button_tag "Browse", class: "btn btn-secondary", type: "button", id: "browse-btn" %>
      </div>
    </div>
    <div class="invalid-feedback"></div>
  </div>

  <div class="form-group">
    <%= f.check_box :response %>
    <%= f.label :response %>
    <div class="invalid-feedback"></div>
  </div>

  <h2 class="text-center">Guests</h2>

  <%= f.fields_for :guests, @item.guests do |fg| %>
    <div class="form-group">
      <%= fg.label :name %>
      <%= fg.text_field :name, class: "form-control", required: true, autocomplete: "off" %>
      <div class="invalid-feedback"></div>
    </div>
    <div class="form-group">
      <%= fg.check_box :attending %>
      <%= fg.label :attending %>
      <div class="invalid-feedback"></div>
    </div>
    <div class="form-group">
      <%= fg.check_box :day_guest %>
      <%= fg.label :day_guest %>
      <div class="invalid-feedback"></div>
    </div>
    <div class="form-group">
      <%= fg.label :family %>
      <%= fg.collection_select :family_id, Family.all, :id, :name, {}, { class: "form-control", required: true } %>
      <div class="invalid-feedback"></div>
    </div>
  <% end %>

  <div class="form-group">
    <%= link_to "Back", admin_families_path, class: "btn btn-outline-secondary" %>
    <%= f.submit "Save", class: "btn btn-outline-primary float-right" %>
  </div>
<% end %>

app/views/admin/families/qrcodes.html.erb
<table class="table table-borderless">
  <tbody>
    <% @families.in_groups_of(2).each do |group| %>
      <tr style="page-break-inside: avoid !important;">
        <% group.compact.each do |family| %>
          <% uuid_arr = family.uuid.upcase.split("") %>
          <td class="text-center">
            <div class="mt-3">
              <h4>bruiloftsamuelencorine.nl</h4>
              <div>
                <span>code</span>
                <h4 class="mr-2"> 
                  <span class="mr-2">
                    <%= uuid_arr[0] %>
                    <%= uuid_arr[1] %>
                    <%= uuid_arr[2] %>
                  </span>
                  <span>
                    <%= uuid_arr[3] %>
                    <%= uuid_arr[4] %>
                    <%= uuid_arr[5] %>
                  </span>
                </h4>
              </div>
            </div>
            <hr />
            <div class="mt-4">
              <%= raw family.qrcode %>
            </div>
            <div class="mt-5">
              <hr />
              <%= family.name %>
            </div>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
<table

app/views/admin/families/show.html.erb
<%= provide(:title, "Wedding | Family #{@family.name}") %>

<%= render 'breadcrumb' %>

<div class="d-flex justify-content-center mt-3">
  <h2>Family</h2>
</div>

<div class="d-flex flex-row-reverse mt-2 mb-2">
  <%= link_to "Delete", admin_family_path(@family), method: :delete, class: "btn btn-outline-primary ml-2", data: { confirm: "Are you sure?" } %>
  <%= link_to "Edit", edit_admin_family_path(@family), class: "btn btn-outline-secondary" %>
</div>

<div class="d-flex">
  <table class="table table-striped">
    <tbody>
    <tr>
      <td colspan="2">
        <strong>Family details</strong>
      </td>
    </tr>
    <tr>
      <th>Family</th>
      <td><%= @family.name %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= mail_to @family.email %></td>
    </tr>
    <tr>
      <th>Response</th>
      <td><%= boolean_icon @family.response %></td>
    </tr>
    <tr>
      <th>uuid</th>
      <td><%= @family.uuid %></td>
    </tr>
    <tr>
      <th>Guests</th>
      <td>
        <div class="d-flex mt-1">
          <div><strong>Name</strong></div>
          <div class="ml-auto"><strong>Attending</strong></div>
        </div>
        <% @family.guests.each do |guest| %>
          <div class="d-flex m-1">
            <div>
              <%= link_to guest.name, admin_guest_path(guest) %>
            </div>
            <div class="ml-auto mr-4">
              <%= boolean_icon guest.attending %>
            </div>
          </div>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>Message</th>
      <td><%= link_to @family.message.content, admin_message_path(@family.message) rescue "none" %></td>
    </tr>
    <tr>
      <th>Allergien</th>
      <td><%= @family.allergies %></td>
    </tr>
    <tr>
      <th>Photo</th>
      <% if @family.photo.attached? %>
        <td><%= image_tag @family.photo, class: "thumbnail" %></td>
      <% else %>
        <td>none</td>
      <% end %>
    </tr>
    <tr>
      <th>QRCode</th>
      <td class="text-center">
        <div class="ml-auto mr-auto qrcode">
          <%= raw @family.qrcode %>
        </div>
      </td>
    </tr>
    </tbody>
  </table>
</div>