config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'families#index'

  get 'admin', to: 'admin/dashboards#index'
  get 'admin/dashboard', to: 'admin/dashboards#index'

  namespace :admin do
    resources :families do
      collection { post :import }
      collection { get :qrcodes, defaults: { format: :pdf } }
    end
    resources :guests
    resources :messages
    resources :posts
  end

  resources :families, only: %i[index update] do
    collection { get :login }
    resources :guests, only: %i[show update]
    resources :messages, only: %i[create show update]
  end
  resources :posts
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :family

  validates :name, presence: true

  scope :is_attending, -> { where(attending: true) }
  scope :day_guests_attending, -> { where(day_guest: true, attending: true) }
  scope :evening_guests_attending, -> { where(day_guest: false, attending: true) }
  scope :day_guests_not_attending, -> { where(day_guest: true, attending: false).or(Guest.where(day_guest: true, attending: nil)) }
  scope :evening_guests_not_attending, -> { where(day_guest: false, attending: false).or(Guest.where(day_guest: false, attending: nil)) }
  scope :not_attending, -> { where(attending: false).or(Guest.where(attending: nil)) }
end

app/controllers/admin/guests_controller.rb
class Admin::GuestsController < AdminController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  def index
    @guests = Guest.all
    @guests.where!("name ILIKE ?", "%#{params[:search]}%") if params[:search]
    @target = params[:target] if params[:target]
    @guests = @guests.order(params[:order]).page(params[:page]).per_page(20)
    @items = @guests
  end

  def show
    respond_with :admin, @guest
  end

  def new
    @item = Guest.new
  end

  def create
    @guest = Guest.create guest_params
    respond_with :admin, @guest
  end

  def edit
    respond_with @guest
  end

  def update
    @guest.update guest_params
    respond_with :admin, @guest
  end

  def destroy
    @guest.destroy
    redirect_to admin_guests_path
  end

  private

  def guest_params
    params.require(:guest).permit :name, :attending, :day_guest, :family_id
  end

  def set_guest
    @guest = Guest.find params[:id]
    @item = @guest
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
end

app/views/admin/guests/_form.html.erb
<%= form_for [:admin, @item], html: { class: "needs-validation", novalidate: true } do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: true, autocomplete: "off" %>
    <div class="invalid-feedback"></div>
  </div>
  <div class="form-group">
    <%= f.check_box :attending %>
    <%= f.label :attending %>
    <div class="invalid-feedback"></div>
  </div>
  <div class="form-group">
    <%= f.check_box :day_guest %>
    <%= f.label :day_guest %>
    <div class="invalid-feedback"></div>
  </div>
  <div class="form-group">
    <%= f.label :family %>
    <%= f.collection_select :family_id, Family.all, :id, :name, {}, { class: "form-control", required: true } %>
    <div class="invalid-feedback"></div>
  </div>
  <%= link_to "Back", admin_guests_path, class: "btn btn-outline-secondary" %>
  <%= f.submit "Save", class: "btn btn-outline-primary float-right" %>
<% end %>

app/views/admin/guests/_guest.html.erb
<li class="list-group-item">
  <div class="d-flex flex-row">
    <div>
      <%= link_to guest.name, admin_guest_path(guest) %>
    </div>
    <div class='ml-auto'>
      <div class="text-right"><%= badge_attending guest %></div>
    </div>
  </div>
  <div class='d-flex flex-row'>
    <div><small><%= link_to guest.family.name, admin_family_path(guest.family), style: 'color:#6c757d' %></small></div>
    <div class='text-muted'><small>&ensp;&bull;&ensp; Day guest: &ensp;<%= boolean_icon guest.day_guest %></small></div>
  </div>
</li>
<tr>
</tr>

app/views/admin/guests/show.html.erb
<%= provide(:title, "Guest from #{@guest.family.name}") %>

<%= render 'breadcrumb' %>

<div class="d-flex justify-content-center mt-3">
  <h2>Guest</h2>
</div>

<div class="d-flex flex-row-reverse mt-2 mb-2">
  <%= link_to "Delete", admin_guest_path(@guest), method: :delete, class: "btn btn-outline-primary float-right ml-2", data: { confirm: "Are you sure?" } %>
  <%= link_to "Edit", edit_admin_guest_path(@guest), class: "btn btn-outline-secondary float-right" %>
</div>

<div class="d-flex">
  <table class="table table-striped">
    <tbody>
      <tr>
        <th colspan="2">Guest from <%= @guest.family.name %></th>
      </tr>
      <tr>
        <th>Name</th>
        <td><%= @guest.name %></td>
      </tr>
      <tr>
        <th>Attending</th>
        <td><%= boolean_icon @guest.attending %></td>
      </tr>
      <tr>
        <th>Day guest</th>
        <td><%= boolean_icon @guest.day_guest %></td>
      </tr>
      <tr>
        <th>Family</th>
        <td><%= link_to @guest.family.name, admin_family_path(@guest.family) %></td>
      </tr>
    </tbody>
  </table>
</div>