config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'families#index'

  get 'admin', to: 'admin/dashboards#index'
  get 'admin/dashboard', to: 'admin/dashboards#index'

  namespace :admin do
    resources :families do
      collection { post :import }
      collection { get :qrcodes, defaults: { format: :pdf } }
    end
    resources :guests
    resources :messages
    resources :posts
  end

  resources :families, only: %i[index update] do
    collection { get :login }
    resources :guests, only: %i[show update]
    resources :messages, only: %i[create show update]
  end
  resources :posts
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < AdminController

  def index
    @responded = Family.responded
    @awaiting_respone = Family.not_responded
    @family_guests_present = Family.joins(:guests).where("guests.attending = ?", true).uniq
    @family_guests_absent = Family.joins(:guests).where("guests.attending is null OR guests.attending = ?", false).uniq
    @messages = Message.all
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def percentage(part, total)
    total.zero? ? 0 : part.to_f / total.to_f * 100
  end
end

app/views/admin/dashboards/_search.html.erb
<input type='text' 
       id="search" 
       class='form-control' 
       placeholder='Search...' 
       autocomplete='off' 
       data-target='items-collection' 
       data-search-path='<%= request.env['PATH_INFO'] %>'
       onKeyup='handleKeyUpSearch(this)' />

app/views/admin/dashboards/_search_bar.html.erb
<div class="col-12 col-md-6">
  <div class="ml-auto mt-1">
    <div class="input-group">
      <%= render 'admin/dashboards/search' %>
      <% if ['families', 'guests'].include?(controller_name) %>
        <div class="input-group-append">
          <button class="btn btn-outline-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-hashpop="true" aria-expanded="false">Sort</button>
          <div class="dropdown-menu">
            <% if controller_name == 'families' %>
              <%= link_to "Name", admin_families_path(order: "name"), class: "dropdown-item" %>
              <%= link_to "Email", admin_families_path(order: "email"), class: "dropdown-item" %>
              <%= link_to "Response", admin_families_path(order: "response"), class: "dropdown-item" %>
              <%= link_to "UUID", admin_families_path(order: "uuid"), class: "dropdown-item" %>
              <%= link_to "Allergien", admin_families_path(order: "allergies"), class: "dropdown-item" %>
            <% elsif controller_name == 'guests' %>
              <%= link_to "Name", admin_guests_path(order: "name"), class: "dropdown-item" %>
              <%= link_to "Attending", admin_guests_path(order: "atteding"), class: "dropdown-item" %>
              <%= link_to "Day guest", admin_guests_path(order: "day_guest"), class: "dropdown-item" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/dashboards/index.html.erb
<%= render 'breadcrumb' %>
<div class="d-flex justify-content-center mt-3">
  <div><h2 class="">Dashboard</h2></div>
</div>

<div class="row">
  <!-- Responded -->
  <div class="col-sm-12 col-md-6 mb-2">
    <ul class="list-group dashboard-list">
      <li class="list-group-item bg-light">
        <span>Responsed</span>
        <span class="badge badge-primary float-right">Families</span>
      </li>
      <li class="list-group-item d-flex justify-content-lg-around flew-row">
        <div class="dashboard-chart" id="chart-response" data-percentage="<%= percentage @responded.count, Family.all.count %>"></div>
        <div class="mt-2">
          <table class="table table-borderless table-sm">
            <tr>
              <th>Responses</th>
              <td><%= @responded.count %></td>
            </tr>
          </table>
          <%= button_tag "List", type: "button", class: "btn btn-primary btn-block", data: { toggle: "modal", target: "#repsonsed-modal" } %>
        </div>       
      </li>
    </ul>
  </div>

  <div class="modal fade" id="repsonsed-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Families that reponded</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul class="list-group">
            <% @responded.order(:name).each do |family| %>
              <li class="list-group-item dashboard-list-item">
                <%= link_to family.name, admin_family_path(family) %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Awaiting response -->
  <div class="col-sm-12 col-md-6 mb-2">
    <ul class="list-group dashboard-list">
      <li class="list-group-item bg-light">
        <span>Awaiting response</span>
        <span class="badge badge-primary float-right">Families</span>
      </li>
      <li class="list-group-item d-flex justify-content-lg-around flex-row">
        <div class="dashboard-chart" id="chart-awaiting" data-percentage="<%= percentage @awaiting_respone.count, Family.all.count %>"></div>
        <div class="mt-2">
          <table class="table table-borderless table-sm">
            <tr>
              <th>Awaiting response</th>
              <td><%= @awaiting_respone.count %></td>
            </tr>
          </table>
          <%= button_tag "List", type: "button", class: "btn btn-primary btn-block", data: { toggle: "modal", target: "#awaiting-repsonse-modal" } %>
        </div>
      </li>
    </ul>
  </div>

  <div class="modal fade" id="awaiting-repsonse-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Families awaiting response</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul class="list-group">
            <% @awaiting_respone.order(:name).each do |family| %>
              <li class="list-group-item dashboard-list-item">
                <%= link_to family.name, admin_family_path(family)  %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Present -->
<div class="row">
  <div class="col-sm-12 col-md-6 mb-2">
    <ul class="list-group dashboard-list">
      <li class="list-group-item bg-light">
        <span>Attending</span>
        <span class="badge badge-primary float-right">Guests</span>
      </li>
      <li class="list-group-item d-flex justify-content-lg-around flex-row">
        <div class="dashboard-chart" id="chart-attending" data-percentage="<%= percentage Guest.is_attending.count, Guest.all.count %>"></div>
        <div class="mt-2">
          <table class="table table-borderless table-sm">
            <tr>
              <td>Day guests</td>
              <td><%= Guest.day_guests_attending.count %></td>
            </tr>
            <tr>
              <td>Evening guests</td>
              <td><%= Guest.evening_guests_attending.count %></td>
            </tr>
            <tr>
              <th>Total</th>
              <td><%= Guest.is_attending.count %></td>
            </tr>
          </table>
          <%= button_tag "List", type: "button", class: "btn btn-primary btn-block", data: { toggle: "modal", target: "#attending-guests-modal" } %>
        </div>
      </li>
    </ul>
  </div>

  <div class="modal fade" id="attending-guests-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Guests attending</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul class="list-group">
            <% @family_guests_present.each do |family| %>
              <li class="list-group-item dashboard-list-item d-flex flex-row">
                <div>
                  <strong><%= link_to family.name, admin_family_path(family) %></strong>
                </div>
                <div class="ml-auto"><%= response_badge(family) %></div>
              </li>
              <% family.guests.is_attending.each do |guest| %>
                <li class="list-group-item dashboard-list-item">
                  <%= link_to guest.name, admin_guest_path(guest), class: "ml-3" %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Absent -->
  <div class="col-sm-12 col-md-6 mb-2">
    <ul class="list-group dashboard-list">
      <li class="list-group-item bg-light">
        <span>Absent<span>
        <span class="badge badge-primary float-right">Guests</span>
      </li>
      <li class="list-group-item d-flex justify-content-lg-around flex-row">
        <div class="dashboard-chart" id="chart-absent" data-percentage="<%= percentage Guest.not_attending.count, Guest.all.count %>"></div>
        <div class="mt-2">
          <table class="table table-borderless table-sm">
            <tr>
              <td>Day guests</td>
              <td><%= Guest.day_guests_not_attending.count %></td>
            </tr>
            <tr>
              <td>Evening guests</td>
              <td><%= Guest.evening_guests_not_attending.count %></td>
            </tr>
            <tr>
              <th>Total</th>
              <td><%= Guest.not_attending.count %></td>
            </tr>
          </table>
          <%= button_tag "List", type: "button", class: "btn btn-primary btn-block", data: { toggle: "modal", target: "#absent-guests-modal" } %>
        </div>
      </li>
    </ul>
  </div>

  <div class="modal fade" id="absent-guests-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Guests absent</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul class="list-group">
            <% @family_guests_absent.each do |family| %>
              <li class="list-group-item dashboard-list-item d-flex flex-row">
                <div>
                  <strong><%= link_to family.name, admin_family_path(family) %></strong>
                </div>
                <div class="ml-auto"><%= response_badge(family) %></div>
              </li>
              <% family.guests.not_attending.each do |guest| %>
                <li class="list-group-item dashboard-list-item">
                  <%= link_to guest.name, admin_guest_path(guest), class: "ml-3" %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(".dashboard-chart").each((i, chart) => {
    const id = $(chart).attr("id");
    
    percentageChart("#" + id);
  });
  
  // TODO: needed if Bootstrap modal is open on page back it's not responding
  $(window).on("popstate", () => {
    window.location.reload();
  });
</script>