config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'families#index'

  get 'admin', to: 'admin/dashboards#index'
  get 'admin/dashboard', to: 'admin/dashboards#index'

  namespace :admin do
    resources :families do
      collection { post :import }
      collection { get :qrcodes, defaults: { format: :pdf } }
    end
    resources :guests
    resources :messages
    resources :posts
  end

  resources :families, only: %i[index update] do
    collection { get :login }
    resources :guests, only: %i[show update]
    resources :messages, only: %i[create show update]
  end
  resources :posts
end

app/views/layouts/_sidenav.html.erb
<div id="mobile-menu" class="p-0 d-sm-none">
  <nav>
    <ul class="list-group">
      <li class="list-group-item">
        <div class="d-flex flex-row-reverse">
          <div><i class="fas fa-times m-2" onclick="closeNav()"></i></div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="d-flex justify-content-center">
          <div><span data-letters="W"></span></div>
          <div class="nav-link-text">&ensp; Wedding</div>
        </div>
      </li>
      <li class="list-group-item">
        <%= link_to admin_dashboard_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div><i class="fas fa-tachometer-alt"></i></div>
            <div class="nav-link-text">&ensp;Dashboard</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to admin_families_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div><i class="fas fa-users"></i></div>
            <div class="nav-link-text">&ensp;Families</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to admin_guests_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div><i class="fas fa-user"></i></div>
            <div class="nav-link-text">&ensp;Guests</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to admin_messages_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div><i class="fas fa-envelope"></i></div>
            <div class="nav-link-text">&ensp;Messages</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to admin_posts_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div><i class="fas fa-paper-plane"></i></div>
            <div class="nav-link-text">&ensp;Posts</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to qrcodes_admin_families_path(format: :pdf) do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div><i class="fas fa-file-pdf"></i></div>
            <div class="nav-link-text">&ensp;Code cards</div>
          </div>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

<div id="desktop-menu" class="col-1 col-md-2 p-0 mt-2 d-none d-sm-inline">
  <nav>
    <ul class="list-group">
      <li class="list-group-item">
        <div class="d-flex justify-content-center">
          <div class="d-inline"><span data-letters="W"></span></div>
          <div class="d-none d-md-inline nav-link-text">&ensp; Wedding</div>
        </div>
      </li>
      <li class="list-group-item">
        <%= link_to admin_dashboard_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div class="d-inline"><i class="fas fa-tachometer-alt"></i></div>
            <div class="d-none d-md-inline nav-link-text">&ensp;Dashboard</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to admin_families_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div class="d-inline"><i class="fas fa-users"></i></div>
            <div class="d-none d-md-inline nav-link-text">&ensp;Families</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to admin_guests_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div class="d-inline"><i class="fas fa-user"></i></div>
            <div class="d-none d-md-inline nav-link-text">&ensp;Guests</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to admin_messages_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div class="d-inline"><i class="fas fa-envelope"></i></div>
            <div class="d-none d-md-inline nav-link-text">&ensp;Messages</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to admin_posts_path do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div class="d-inline"><i class="fas fa-paper-plane"></i></div>
            <div class="d-none d-md-inline nav-link-text">&ensp;Posts</div>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to qrcodes_admin_families_path(format: :pdf) do %>
          <div class="d-flex justify-content-center justify-content-md-start">
            <div class="d-inline"><i class="fas fa-file-pdf"></i></div>
            <div class="d-none d-md-inline nav-link-text">&ensp;Code cards</div>
          </div>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

<script>
  $(document).ready(function() {
    $("nav ul li").removeClass("link-active");
    $("nav").find("a[href='"+window.location.pathname+"']").closest("li").addClass("link-active")
  });
</script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wedding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Parisienne|Source+Sans+Pro" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <%= yield(:head_tags) %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div id="admin-header" class="d-flex flex-row w-100">
          <div id="#open-mobile-nav" class="ml-2 mt-2 d-sm-none" onClick="openNav()">
            <i class="fas fa-bars fa-2x"></i>
          </div>
          <div class="m-2 flex-fill text-center">
            <h3>Wedding</h3>
          </div>
          <% if user_signed_in? %>
            <div class="admin-btns">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-light float-right mt-2 ml-2' %>
              <% if params[:controller].split("/").first != "admin" %>
                <%= link_to "Admin", admin_families_path, class: "btn btn-outline-primary float-right mt-2" %>
              <% end %>
            </div>
          <% end %>
        </div>
        <%= render 'layouts/sidenav' %>
        <div class="col" id="main">
          <div class="mt-2">
            <% if notice %>
              <p class="alert alert-info"><%= notice %></p>
            <% end %>
            <% if flash[:success] %>
              <p class="alert alert-success"><%= flash[:success] %></p>
            <% end %>
            <% if flash[:warning] %>
              <p class="alert alert-warning"><%= flash[:warning] %></p>
            <% end %>
            <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
            <% end %>
          </div>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wedding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Parisienne|Source+Sans+Pro" rel="stylesheet">
    <%= stylesheet_pack_tag 'application/stylesheets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <%= yield(:head_tags) %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col" id="main">
          <div class="mt-2">
            <% if notice %>
              <p class="alert alert-info"><%= notice %></p>
            <% end %>
            <% if flash[:success] %>
              <p class="alert alert-success"><%= flash[:success] %></p>
            <% end %>
            <% if flash[:warning] %>
              <p class="alert alert-warning"><%= flash[:warning] %></p>
            <% end %>
            <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
            <% end %>
          </div>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>